<a href="https://colab.research.google.com/github/arhamxyz/Machine-Learning-Homework/blob/main/WEEK9_Concise_Implementation_of_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install d2l==0.17.0

     |████████████████████████████████| 83 kB 1.4 MB/s 


In [2]:
import numpy as np
import tensorflow as tf
from d2l import tensorflow as d2l

true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [3]:
def load_array(data_arrays, batch_size, is_train=True):  #@save
    """Construct a TensorFlow data iterator."""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [4]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[ 1.8448108 , -0.5819135 ],
        [-1.3105229 , -0.48300982],
        [-1.9893924 , -0.206483  ],
        [ 0.00902979,  0.6035483 ],
        [ 0.04745312,  1.4524261 ],
        [-1.7302972 , -0.8084463 ],
        [ 1.0886055 , -0.00774782],
        [ 0.40453342,  0.79989934],
        [ 2.51887   ,  1.190169  ],
        [ 0.4916394 ,  0.09547692]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 9.856315 ],
        [ 3.2270935],
        [ 0.9147672],
        [ 2.1581297],
        [-0.6576655],
        [ 3.4898334],
        [ 6.405344 ],
        [ 2.2994292],
        [ 5.1883955],
        [ 4.8577147]], dtype=float32)>)

In [5]:
# `keras` is the high-level API for TensorFlow
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

In [6]:
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

In [7]:
loss = tf.keras.losses.MeanSquaredError()

In [8]:
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

In [9]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True), y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000284
epoch 2, loss 0.000095
epoch 3, loss 0.000095


In [10]:
w = net.get_weights()[0]
print('error in estimating w', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('error in estimating b', true_b - b)

error in estimating w tf.Tensor([5.738735e-04 4.005432e-05], shape=(2,), dtype=float32)
error in estimating b [-0.00015163]
